#!/usr/bin/with-contenv bash

# Check if snapserver should get started
if [ "$START_SNAPSERVER" = 'true' ]; then
	exec \
    	s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 1780" \
      	s6-setuidgid abc /usr/bin/snapserver --config /config/snapserver.conf $SNAPSERVER_OPTS
fi
